apiVersion: v2
appVersion: "1.0.0"
name: shortlink-landing
description: Shortlink landing service
version: 0.7.3
kubeVersion: ">= 1.28.0 || >= v1.28.0-0"
keywords:
  - ui
  - shortlink
  - landing
home: https://batazor.github.io/shortlink/
sources:
  - https://github.com/shortlink-org/shortlink
maintainers:
  - email: batazor111@gmail.com
    name: batazor
    url: batazor.ru
engine: gotpl
type: application
deprecated: false
dependencies:
  - name: shortlink-template
    version: 0.8.6
    repository: "file://../shortlink-template"
