apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: dual-role
  labels:
    strimzi.io/cluster: shortlink
spec:
  replicas: 3
  roles:
    - controller
    - broker
  storage:
    type: ephemeral
