# Load artifacts from multi-pipeline
# TODO: Watch https://gitlab.com/gitlab-org/gitlab/issues/202093#note_291607385
load artifacts golang:
  stage: .post
  script:
    - echo "Load artifacts from multi-pipeline"
  needs:
    - pipeline: $UPSTREAM_PIPELINE_ID
      job: golint
      artifacts: true
    - pipeline: $UPSTREAM_PIPELINE_ID
      job: gotest
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success

load artifacts sast:
  stage: .post
  script:
    - echo "Load artifacts from multi-pipeline"
  needs:
    - pipeline: $UPSTREAM_PIPELINE_ID
      job: code_quality
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
