x-network: &network
  networks:
    - ${DOCKER_NETWORK}
  dns:
    - ${DNS_IP}
  dns_search: ${DNS_SEARCH}

services:

  localstack:
    <<: *network
    image: localstack/localstack:3.2.3
    container_name: localstack
    environment:
      - SERVICES=s3
    ports:
      - "4566:4566"
    volumes:
      - ./data/localstack:/tmp/localstack"
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: "bash -c 'AWS_ACCESS_KEY_ID=test AWS_SECRET_ACCESS_KEY=test aws --endpoint-url=http://localhost:4566 s3 ls'"
      retries: 15
      interval: 10s
