version: '2.4'

x-network: &network
  networks:
    - simple
  dns:
    - ${DNS_IP}
  dns_search: ${DNS_SEARCH}

services:

  spicedb:
    <<: *network
    depends_on:
      - coredns
      - spicedb_migrate
    image: authzed/spicedb
    command: serve
    container_name: spicedb
    restart: always
    ports:
      - 8080:8080
      - 9091:9090
      - 50151:50051
    environment:
      SPICEDB_GRPC_PRESHARED_KEY: secret-shortlink-preshared-key
      SPICEDB_DATASTORE_ENGINE: postgres
      SPICEDB_DATASTORE_CONN_URI: postgres://postgres:shortlink@postgres:5432/shortlink?sslmode=disable
      SPICEDB_DISPATCH_CACHE_METRICS: true
      SPICEDB_DISPATCH_CLUSTER_METRICS: true
      SPICEDB_NS_CACHE_METRICS: true
      SPICEDB_METRICS_ENABLED: true
      # SPICEDB_OTEL_PROVIDER: jaeger
      SPICEDB_OTEL_SAMPLE_RATIO: 1
      OTEL_EXPORTER_OTLP_ENDPOINT: jaeger-agent:4317
      SPICEDB_LOG_LEVEL: trace

  spicedb_migrate:
    <<: *network
    depends_on:
      - coredns
      - postgres
    image: authzed/spicedb
    command: "migrate head"
    container_name: spicedb_migrate
    restart: on-failure
    environment:
      SPICEDB_DATASTORE_ENGINE: postgres
      SPICEDB_DATASTORE_CONN_URI: postgres://postgres:shortlink@postgres:5432/shortlink?sslmode=disable
