version: '2.4'

x-network: &network
  networks:
    - simple
  dns:
    - ${DNS_IP}
  dns_search: ${DNS_SEARCH}

services:

  temporal:
    <<: *network
    depends_on:
      - coredns
      - postgres
    image: temporalio/auto-setup:1.22.1
    restart: on-failure
    container_name: temporal
    environment:
      DB: postgresql
      DB_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PWD: shortlink
      POSTGRES_DB: shortlink
      POSTGRES_SEEDS: postgres
      DYNAMIC_CONFIG_FILE_PATH: config/dynamicconfig/development-sql.yaml
      BIND_ON_IP: 0.0.0.0
      TEMPORAL_BROADCAST_ADDRESS: 0.0.0.0
    ports:
      - 7233:7233
    volumes:
      - ./ops/docker-compose/tooling/saas/temporal/config:/etc/temporal/config/dynamicconfig

  temporal-admin-tools:
    <<: *network
    depends_on:
      - coredns
      - temporal
    image: temporalio/admin-tools:1.22.1
    restart: on-failure
    container_name: temporal-admin-tools
    environment:
      TEMPORAL_ADDRESS: temporal:7233
      TEMPORAL_CLI_ADDRESS: temporal:7233
    stdin_open: true
    tty: true

  temporal-ui:
    <<: *network
    depends_on:
      - coredns
      - temporal
    image: temporalio/ui:2.20.0
    restart: on-failure
    container_name: temporal-ui
    environment:
      TEMPORAL_ADDRESS: temporal:7233
      TEMPORAL_CLI_ADDRESS: temporal:7233
    ports:
      - 8080:8080
