# global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'shortlink'

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'victoria'
    static_configs:
      - targets:
          - localhost:8428

  - job_name: 'coredns'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      - targets: ['coredns:9153']

  - job_name: 'grafana'
    dns_sd_configs:
      - names:
          - 'grafana'
        type: 'A'
        port: 3000
        refresh_interval: 10s

  - job_name: 'jaeger-agent'
    static_configs:
      - targets: ['jaeger-agent:3100']

  - job_name: node_exporter
    static_configs:
      - targets: ['node-exporter:9100']

  # Load a directory of JSON configs
  - job_name: 'stub'  # This is a default value, it is mandatory.
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/*.json
