apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: internal-gateway
spec:
  gatewayClassName: cilium
  listeners:
    - name: grpc
      hostname: "*.shortlink"
      port: 50051
      protocol: HTTPS
      tls:
        certificateRefs:
          - kind: Secret
            group: ""
            name: internal-gateway-cert
      allowedRoutes:
        namespaces:
          from: Same
