services:

  rethinkdb:
    depends_on:
      - coredns
    image: rethinkdb:2.4-buster-slim
    init: true
    restart: on-failure
    container_name: rethinkdb
    ports:
      - "28080:8080" # UI port
      - "28015:28015"
      - "29015:29015"
    networks:
      simple:
        ipv4_address: ${DATABASE_IP}
    dns:
      - ${DNS_IP}
    dns_search: ${DNS_SEARCH}
#    logging:
#      driver: fluent-bit
#      options:
#        tag: rethinkdb
