version: '2.4'

include:
  - ./ops/docker-compose/mq/zookeeper/zookeeper.yaml

x-network: &network
  networks:
    - simple
  dns:
    - ${DNS_IP}
  dns_search: ${DNS_SEARCH}

services:

  # Init cluster metadata
  pulsar-init:
    <<: *network
    depends_on:
      - coredns
      - zookeeper
    image: apachepulsar/pulsar:latest
    container_name: pulsar-init
    hostname: pulsar-init
    command: >
      bin/pulsar initialize-cluster-metadata \
               --cluster cluster-a \
               --zookeeper zookeeper:2181 \
               --configuration-store zookeeper:2181 \
               --web-service-url http://broker:8080 \
               --broker-service-url pulsar://broker:6650

  # Start bookie
  bookie:
    <<: *network
    depends_on:
      - coredns
      - zookeeper
      - pulsar-init
    image: apachepulsar/pulsar:latest
    command: bash -c "bin/apply-config-from-env.py conf/bookkeeper.conf && exec bin/pulsar bookie"
    container_name: bookie
    restart: on-failure
    environment:
      clusterName: cluster-a
      zkServers: zookeeper:2181
      metadataServiceUri: metadata-store:zk:zookeeper:2181
      advertisedAddress: bookie
      BOOKIE_MEM: "-Xms512m -Xmx512m -XX:MaxDirectMemorySize=256m"

  # Start broker
  broker:
    <<: *network
    depends_on:
      - coredns
      - zookeeper
      - pulsar-init
    image: apachepulsar/pulsar:latest
    command: bash -c "bin/apply-config-from-env.py conf/broker.conf && exec bin/pulsar broker"
    container_name: broker
    hostname: broker
    restart: on-failure
    environment:
      metadataStoreUrl: zk:zookeeper:2181
      zookeeperServers: zookeeper:2181
      clusterName: cluster-a
      managedLedgerDefaultEnsembleSize: 1
      managedLedgerDefaultWriteQuorum: 1
      managedLedgerDefaultAckQuorum: 1
      advertisedAddress: broker
      advertisedListeners: "external:pulsar://127.0.0.1:6650"
      PULSAR_MEM: "-Xms512m -Xmx512m -XX:MaxDirectMemorySize=256m"
    ports:
      - "6650:6650"
      - "8080:8080"

  # UI
  pulsar-manager:
    <<: *network
    depends_on:
      - coredns
      - zookeeper
      - pulsar-init
    image: apachepulsar/pulsar-manager:v0.4.0
    container_name: pulsar-manager
    restart: on-failure
    environment:
      SPRING_CONFIGURATION_FILE: /pulsar-manager/pulsar-manager/application.properties
    ports:
      - 9527:9527
      - 7750:7750

  pulsar-manager-add-user:
    <<: *network
    depends_on:
      - coredns
      - pulsar-manager
    image: curlimages/curl:latest
    environment:
      - USER_NAME=admin
      - USER_PASSWORD=apachepulsar
      - USER_EMAIL=username@test.org
      - USER_DESCRIPTION=test
    command: ["sh", "/add-pulsar-manager-user.sh"]
    volumes:
      - ./ops/docker-compose/mq/pulsar/conf/add-pulsar-manager-user.sh:/add-pulsar-manager-user.sh
