apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: shortlink
spec:
  postgresVersion: 16
  instances:
    - name: shortlink
      metadata:
        annotations:
          replicator.v1.mittwald.de/replicate-to: "shortlink"
      dataVolumeClaimSpec:
        storageClassName: local-path
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
  backups:
    pgbackrest:
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              storageClassName: local-path
              accessModes:
                - "ReadWriteOnce"
              resources:
                requests:
                  storage: 1Gi
  proxy:
    pgBouncer:
      replicas: 1
      port: 5432
      poolSize: 10
      config:
        global:
          pool_mode: transaction
      resources:
        requests:
          cpu: 2m
          memory: 56Mi
        limits:
          cpu: 100m
          memory: 128Mi
  monitoring:
    pgmonitor:
      exporter:
        image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.5.0-0
  users:
    - name: shortlink
      databases:
        - link
        - support
        - billing
