x-network: &network
  networks:
    - ${DOCKER_NETWORK}
  dns:
    - ${DNS_IP}
  dns_search: ${DNS_SEARCH}

services:

  pyroscope:
    <<: *network
    depends_on:
      - coredns
    image: grafana/pyroscope:latest
    command:
      - '-config.file=/etc/pyroscope.yml'
    container_name: pyroscope
    restart: on-failure
    environment:
      JAEGER_AGENT_HOST: tempo
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
    ports:
      - "4040:4040"
    volumes:
      - ./ops/docker-compose/tooling/observability/grafana/conf/pyroscope/pyroscope.yml:/etc/pyroscope.yml
