apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: shortlink-metadata
build:
  local:
    useBuildkit: true
  artifacts:
  - image: shortlink-metadata
    context: ../../
    docker:
      dockerfile: ops/dockerfile/go.Dockerfile
      buildArgs:
          CMD_PATH: "./cmd/metadata"
    sync:
      infer:
        - 'cmd/metadata/**'
        - 'pkg/**'
        - 'internal'
deploy:
  helm:
    releases:
    - name: shortlink-metadata
      namespace: shortlink
      chartPath: ../Helm/shortlink-link/metadata
      wait: true
      artifactOverrides:
        image: shortlink-metadata
      setValueTemplates:
        deploy.image.repository: "{{.IMAGE_REPO3}}"
        deploy.image.tag: "{{.IMAGE_TAG3}}"

