apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: sidecar
spec:
  mode: sidecar
  securityContext:
    capabilities:
      add:
        - SYS_PTRACE
    privileged: true
    runAsUser: 0
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    exporters:
      otlp:
        endpoint: otel-collector-collector.grafana.svc.cluster.local:4317
        tls:
          insecure: true
    service:
      telemetry:
        logs:
          level: info
      pipelines:
        traces:
          receivers:
          - otlp
          exporters:
          - otlp
