apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shortlink-shop-common
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: shortlink
  destination:
    name: ''
    namespace: shortlink-shop
    server: 'https://kubernetes.default.svc'
  source:
    path: ops/Helm/shortlink-shop/common
    repoURL: 'https://github.com/shortlink-org/shortlink'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - redis.values.yaml
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 2
      backoff:
        duration: 10s
        maxDuration: 3m0s
        factor: 2
  ignoreDifferences:
    - group: kyverno.io
      kind: ClusterPolicy
      jqPathExpressions:
        - .spec.rules[] | select(.name|test("autogen-."))
    - kind: Secret
      name: shortlink-postgres-pguser-grafana
      jqPathExpressions:
        - .data
