apiVersion: v2
appVersion: "1.0.0"
name: tracetest  
version: 0.2.3   
kubeVersion: ">= 1.28.0 || >= v1.28.0-0"
keywords:
  - flux
maintainers:
  - email: batazor111@gmail.com
    name: batazor
    url: batazor.ru
engine: gotpl
type: application
deprecated: false
dependencies:
  - name: tracetest
    version: 0.3.4
    repository: https://kubeshop.github.io/helm-charts
    condition: tracetest.enabled
  - name: oauth2-proxy
    version: 6.23.1
    repository: https://oauth2-proxy.github.io/manifests
    condition: oauth-proxy.enabled
