oauth2-proxy:
  enabled: true

  resources:
    limits:
      cpu: 250m
      memory: 50Mi
    requests:
      cpu: 25m
      memory: 50Mi

  extraEnv:
    - name: OAUTH2_PROXY_EMAIL_DOMAINS
      value: "*"
    - name: OAUTH2_PROXY_PROVIDER
      value: github
    - name: OAUTH2_PROXY_SCOPE
      value: "user:email"
    - name: OAUTH2_PROXY_GITHUB_ORG
      value: "shortlink-org"
    - name: OAUTH2_PROXY_REDIRECT_URL
      value: "https://tracetest.shortlink.best/oauth2/callback"
    - name: OAUTH2_PROXY_HTTP_ADDRESS
      value: '0.0.0.0:4180'

  metrics:
    enabled: true
    servicemonitor:
      enabled: true
      labels:
          release: prometheus-operator

  ingress:
    enabled: true

    className: nginx

    annotations:
      cert-manager.io/cluster-issuer: cert-manager-production
      nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
      nginx.ingress.kubernetes.io/enable-opentelemetry: "true"

    path: /oauth2
    pathType: Prefix

    hosts:
      - tracetest.shortlink.best

    tls:
      - secretName: oauth-proxy-tls
        hosts:
          - tracetest.shortlink.best
