version: '2.4'

x-network: &network
  networks:
    - simple
  dns:
    - ${DNS_IP}
  dns_search: ${DNS_SEARCH}

services: {}

# Backup
# Docs: https://github.com/wal-g/wal-g/blob/master/docs/PostgreSQL.md
# Bitnami delete the image from docker hub
# wal-g:
#  <<: *network
#  depends_on:
#    - coredns
#    - postgres
#  image: docker.io/bitnami/wal-g:1.1.0
#  container_name: wal-g
#  init: true
#  profiles:
#    - postgres
#  restart: on-failure
#  user: root
#  command: --walg-file-prefix=/tmp/backups --pghost=postgres --pguser=postgres --pgpassword=shortlink --pgdatabase=shortlink backup-push /var/lib/postgresql/data
#  volumes:
#    - /data/shortlink/store/postgres/data:/var/lib/postgresql/data
#    - /data/shortlink/store/postgres/backups:/tmp/backups
