apiVersion: v2
appVersion: "1.0.0"
name: shortlink-api-grpc-web
description: ShortLink API service
version: 0.13.1
kubeVersion: ">= 1.28.0 || >= v1.28.0-0"
keywords:
  - api
  - shortlink
  - grpc-web
home: https://batazor.github.io/shortlink/
sources:
  - https://github.com/shortlink-org/shortlink
maintainers:
  - email: batazor111@gmail.com
    name: batazor
    url: batazor.ru
engine: gotpl
type: application
deprecated: false
dependencies:
  - name: shortlink-template
    version: 0.8.11
    repository: "file://../../shortlink-template"
