# Common default values for kubescape.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

kubescape:
  enabled: true

  global:
    networkPolicy:
      enabled: false
      createEgressRules: false

  capabilities:
    continuousScan: enable
    seccompGenerator: enable
    vexGeneration: enable
    autoUpgrading: enable

  configurations:
    persistence: disable

  clusterName: shortlink

  kubescape:
    prometheusAnnotation:
      enabled: true

    labels:
      release: prometheus-operator

    serviceMonitor:
      enabled: true

  persistence:
    storageClass: local-path

  operator:
    resources:
      requests:
        cpu: 70m
        memory: 120Mi
