# Common default values for kubescape.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

kubescape:
  enabled: true

  global:
    networkPolicy:
      enabled: true
      createEgressRules: true

  capabilities:
    continuousScan: enable
    runtimeObservability: enable
    networkPolicyService: enable
    networkGenerator: enable
    seccompGenerator: enable
    vexGeneration: enable

  clusterName: shortlink

  kubescape:
    labels:
      release: prometheus-operator

    serviceMonitor:
      enabled: true

  configurations:
    otelUrl: http://grafana-tempo.grafana:4317

  persistence:
    storageClass: local-path

  operator:
    resources:
      requests:
        cpu: 70m
        memory: 120Mi
