apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: spicedb-postgres
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  postgresVersion: 16
  metadata:
    annotations:
      sidecar.istio.io/inject: "false"
  instances:
    - name: spicedb
      replicas: 1
      metadata:
        annotations:
          sidecar.istio.io/inject: "false"
      dataVolumeClaimSpec:
        storageClassName: local-path
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          track_commit_timestamp: "on"
          shared_preload_libraries: auto_explain,pgaudit,pg_stat_statements
  backups:
    pgbackrest:
      metadata:
        annotations:
          sidecar.istio.io/inject: "false"
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              storageClassName: local-path
              accessModes:
                - "ReadWriteOnce"
              resources:
                requests:
                  storage: 1Gi
  monitoring:
    pgmonitor:
      exporter:
        image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.5.0-0
  users:
    - name: admin
      databases:
        - postgres
        - spicedb
      options: "SUPERUSER"
    - name: spicedb
      databases:
        - spicedb
      options: "SUPERUSER"
