apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources: []

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    isDefault: true
    url: http://prometheus:9090
    editable: true
    jsonData:
      timeInterval: 10s
      queryTimeout: 30s
      httpMethod: POST
      alertmanagerUid: alertmanager
      incrementalQuerying: true
      exemplarTraceIdDestinations:
        - name: "traceID"
          datasourceUid: tempo

  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      maxLines: 1000
      alertmanagerUid: alertmanager
      derivedFields:
        # Field with an internal link pointing to a data source in Grafana.
        # Right now, Grafana supports only Jaeger and Zipkin data sources as link targets.
        # datasourceUid value can be anything, but it should be unique across all defined data source uids.
        - datasourceUid: tempo
          matcherRegex: 'traceID":"(\w+)'
          name: TraceID
          # url will be interpreted as a query for the datasource
          url: "$${__value.raw}"

        # Field with an external link.
        - matcherRegex: 'traceID":"(\w+)'
          name: TraceID (external)
          url: "http://localhost:16686/trace/$${__value.raw}"

  - name: Tempo
    type: tempo
    uid: tempo
    url: http://jaeger-query:16686
    editable: true
    jsonData:
      lokiSearch:
        datasourceUid: loki
      nodeGraph:
        enabled: true
      search:
        hide: true
      spanBar:
        type: Duration
      serviceMap:
        datasourceUid: prometheus
      tracesToLogs:
        datasourceUid: loki
        filterBySpanID: true
        filterByTraceID: true
        mapTagNamesEnabled: true
      tracesToProfiles:
        customQuery: false
        datasourceUid: pyroscope
        profileTypeId: "process_cpu:cpu:nanoseconds:cpu:nanoseconds"

  - name: Alertmanager
    type: alertmanager
    uid: alertmanager
    editable: true
    url: http://prometheus-alertmanager.prometheus-operator:9093
    readOnly: false
    jsonData:
      implementation: mimir

  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    editable: true
    user: postgres
    password: shortlink
    database: shortlink
    jsonData:
      postgresVersion: 1600
      sslmode: disable
      tlsSkipVerify: true

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200/
    editable: true
    database: shortlink.link.link_view
    jsonData:
      timeField: "@timestamp"
      esVersion: "7.10.0"

  - name: Pyroscope
    type: grafana-pyroscope-datasource
    access: proxy
    uid: pyroscope
    url: http://pyroscope:4040
    jsonData:
      minStep: '15s'


