# Common default values for grafana.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Docs: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
grafana:
  enabled: true
  namespaceOverride: ""

  # Deploy default dashboards.
  ##
  defaultDashboardsEnabled: true

  # adminPassword: shortlink

  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  persistence:
    enabled: true
    storageClassName: local-path
    inMemory:
      enabled: true

  revisionHistoryLimit: 2

  serviceMonitor:
    enabled: true
    selfMonitor: true
    interval: "1m"

    labels:
      release: prometheus-operator

  imageRenderer:
    enabled: true

    revisionHistoryLimit: 2

    securityContext:
      runAsNonRoot: true
      runAsUser: 472
      runAsGroup: 472
      fsGroup: 472

    serviceMonitor:
      enabled: true
      selfMonitor: true
      interval: "1m"

    resources:
      limits:
        cpu: 300m
        memory: 256Mi
      requests:
        cpu: 25m
        memory: 64Mi

  ingress:
    enabled: true

    annotations:
      cert-manager.io/cluster-issuer: cert-manager-production
      nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
      nginx.ingress.kubernetes.io/enable-opentelemetry: "true"

    hosts:
      - grafana.shortlink.best

    path: /

    tls:
      - secretName: grafana-ingress-tls
        hosts:
          - grafana.shortlink.best

  sidecar:
    image:
      tag: 1.26.1
    alerts:
      enabled: true
      searchNamespace: ALL
    dashboards:
      enabled: true
      defaultFolderName: "General"
      searchNamespace: ALL
      folder: /tmp/dashboards
      folderAnnotation: grafana_dashboard_folder
      provider:
        foldersFromFilesStructure: true
    datasources:
      enabled: true
      searchNamespace: ALL
    plugins:
      enabled: true
      searchNamespace: ALL
      skipReload: true
      initPlugins: true
    notifiers:
      enabled: true
      searchNamespace: ALL

  plugins:
    - grafana-polystat-panel
    - grafana-oncall-app
    - cloudflare-app
    - hamedkarbasi93-kafka-datasource
    # infinity: datasource for work with GraphQL, JSON, CSV, XML, HTML formats
    - yesoreyeram-infinity-datasource

  grafana.ini:
    reporting:
      enabled: true

    auth:
      anonymous:
        enabled: true

        # Organization name that should be used for unauthenticated users
        org_name: "Main Org."

        # Role for unauthenticated users, other valid values are `Editor` and `Admin`
        org_role: Viewer

        # Hide the Grafana version text from the footer and help tooltip for unauthenticated users (default: false)
        hide_version: true
