apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: shortlink
scheduler:
  name: ""
spec:
  configuration:
    name: shortlink-env-configuration
  credsSecret:
    name: shortlink-secret
  exposeServices:
    console: true
    minio: true
  features:
    ## Enable S3 specific features such as Bucket DNS which would allow `buckets` to be
    ## accessible as DNS entries of form `<bucketname>.minio.namespace.svc.cluster.local`
    ## This feature is turned off by default
    bucketDNS: true
  mountPath: /export
  pools:
  - name: pool-0
    resources:
      limits:
        memory: 8Gi
      requests:
        memory: 2Gi
    servers: 2
    volumeClaimTemplate:
      metadata:
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: "2684354560"
        storageClassName: local-path
    volumesPerServer: 2
  prometheusOperator:
    annotations:
      release: prometheus-operator
  requestAutoCert: false
  users:
  - name: shortlink-user-0
  - name: testkube-user-0
