apiVersion: v1
kind: Secret
metadata:
  name: shortlink-user
type: Opaque
data:
  ## Tenant base64 access key (minio-tenant-access-key)
  accesskey: {{ .Values.accesskey | b64enc }}
  ## Tenant base64 secret key (minio-tenant-secret-key)
  secretkey: {{ .Values.secretkey | b64enc }}
