apiVersion: v2
appVersion: "1.0.0"
name: shortlink-auth
description: Shortlink Auth Service
version: 0.1.1
kubeVersion: ">= 1.28.0 || >= v1.28.0-0"
keywords:
  - auth
  - permissions
  - shortlink
home: https://batazor.github.io/shortlink/
sources:
  - https://github.com/shortlink-org/shortlink
maintainers:
  - email: batazor111@gmail.com
    name: batazor
    url: batazor.ru
engine: gotpl
type: application
deprecated: false
dependencies:
  - name: shortlink-template
    version: 0.7.0
    repository: "file://../shortlink-template"
