openapi: 3.0.1

servers:
  - url: http://localhost:7070/api
    description: Local server
  - url: https://shortlink.best/api
    description: Production server
  - url: https://shortlink.best/mock
    description: Mock server

# Available options: https://github.com/json-schema-faker/json-schema-faker/tree/master/docs#available-options
x-json-schema-faker:
  locale: en
  min-items: 2
  max-items: 5
  resolve-json-path: true
  useExamplesValue: true

info:
  title: ShortLink API
  description: |
    ShortLink API for managing and retrieving short links.
  contact:
    email: support@swagger.io
    name: ShortLink repository
    url: https://github.com/shortlink-org/shortlink/issues
  license:
    name: MIT
    url: http://www.opensource.org/licenses/MIT

paths:
  /links:
    get:
      summary: List links
      description: Retrieve a list of all short links.
      operationId: listLinks
      tags:
        - Link
      responses:
        '200':
          $ref: '#/components/responses/ListResponse'
        '500':
          $ref: '#/components/responses/InternalServerError'

    post:
      summary: Add link
      description: Add a new short link.
      operationId: addLink
      tags:
        - Link
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddRequest'
      responses:
        '201':
          $ref: '#/components/responses/LinkCreated'
        '400':
          $ref: '#/components/responses/BadRequest'

  /links/{hash}:
    get:
      summary: Get link
      description: Retrieve a specific link by its hash.
      operationId: getLink
      tags:
        - Link
      parameters:
        - $ref: '#/components/parameters/HashParam'
      responses:
        '200':
          $ref: '#/components/responses/LinkDetails'
        '404':
          $ref: '#/components/responses/NotFound'

    put:
      summary: Update link
      description: Update an existing link by its hash.
      operationId: updateLink
      tags:
        - Link
      parameters:
        - $ref: '#/components/parameters/HashParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateRequest'
      responses:
        '200':
          $ref: '#/components/responses/LinkUpdated'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      summary: Delete link
      description: Delete a specific link by its hash.
      operationId: deleteLink
      tags:
        - Link
      parameters:
        - $ref: '#/components/parameters/HashParam'
      responses:
        '204':
          $ref: '#/components/responses/LinkDeleted'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  parameters:
    HashParam:
      name: hash
      in: path
      required: true
      schema:
        type: string
      description: Unique hash of the link.

  responses:
    ListResponse:
      description: A list of links.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ListResponse'
    LinkCreated:
      description: Link created successfully.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AddResponse'
    LinkDetails:
      description: Details of the link.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GetResponse'
    LinkUpdated:
      description: Link updated successfully.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateResponse'
    LinkDeleted:
      description: Link deleted successfully.
    NotFound:
      description: Link not found.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    BadRequest:
      description: Bad request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

  schemas:
    AddRequest:
      type: object
      properties:
        url:
          type: string
          format: uri
          description: The URL to be shortened.
        describe:
          type: string
          description: Optional description of the link.
      required:
        - url

    AddResponse:
      type: object
      properties:
        link:
          $ref: '#/components/schemas/Link'

    GetResponse:
      type: object
      properties:
        link:
          $ref: '#/components/schemas/Link'
      description: Response schema for a single link retrieval.

    Link:
      type: object
      properties:
        hash:
          type: string
          description: Unique hash identifier for the link.
        url:
          type: string
          format: uri
          description: The original URL.
        created_at:
          type: string
          format: date-time
          description: Timestamp when the link was created.
        updated_at:
          type: string
          format: date-time
          description: Timestamp when the link was last updated.
        describe:
          type: string
          description: Description of the link.
      required:
        - hash
        - url
        - created_at

    ListResponse:
      type: object
      properties:
        links:
          type: array
          items:
            $ref: '#/components/schemas/Link'

    UpdateRequest:
      type: object
      properties:
        url:
          type: string
          format: uri
          description: The new URL to update.
        describe:
          type: string
          description: Updated description of the link.
      required:
        - url

    UpdateResponse:
      type: object
      properties:
        link:
          $ref: '#/components/schemas/Link'

    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
          description: Error code representing the type of error.
        message:
          type: string
          description: Human-readable message providing more details about the error.
