openapi: 3.0.1

servers:
  - url: http://localhost:8080/api
    description: Local server
  - url: https://shortlink.best/api
    description: Production server
  - url: https://shortlink.best/mock
    description: Mock server

# Available options: https://github.com/json-schema-faker/json-schema-faker/tree/master/docs#available-options
x-json-schema-faker:
  locale: en
  min-items: 2
  max-items: 5
  resolve-json-path: true
  useExamplesValue: true

info:
  title: ShortLink API
  description: |
    ShortLink API for BFF web service
  version: 0.0.1

tags:
  - name: Link
  - name: Billing
  - name: Referral

paths:
  /links:
    get:
      tags:
        - Link
      summary: Get all links
      description: |
        Get all links
      operationId: getLinks
      parameters:
        - $ref: '#/components/parameters/filter'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Links'
        '404':
          $ref: '#/components/responses/NotFoundError'
#  /cqrs:
#    get:
#      tags:
#        - Link
#      summary: Get all cqrs
#      description: |
#        Get all cqrs
#      operationId: getCqrs
#      parameters:
#        - $ref: '#/components/parameters/limit'
#        - $ref: '#/components/parameters/offset'
#      responses:
#        '200':
#          description: OK
#          content:
#            application/json:
#              schema:
#                $ref: '#/components/schemas/Links'
#        '404':
#          $ref: '#/components/responses/NotFoundError'
#  /sitemap:
#    get:
#      tags:
#        - Link
#      summary: Get all sitemap
#      description: |
#        Get all sitemap
#      operationId: getSitemap
#      parameters:
#        - $ref: '#/components/parameters/limit'
#        - $ref: '#/components/parameters/offset'
#      responses:
#        '200':
#          description: OK
#          content:
#            application/json:
#              schema:
#                $ref: '#/components/schemas/Links'
#        '404':
#          $ref: '#/components/responses/NotFoundError'

components:
  parameters:
    filter:
      name: filter
      in: query
      description: Filter
      required: false
      schema:
        type: object
        format: json
        default: {}

  responses:
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorNotFound'
          example:
            error: Not Found

  schemas:
    Links:
      type: array
      items:
        $ref: '#/components/schemas/Link'

    Link:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 1a2b3c4d-5e6f-7g8h-9i0j-1k2l3m4n5o6p
        url:
          type: string
          format: url
          example: https://shortlink.best
        created_at:
          type: string
          format: date-time
          example: 2021-01-01T00:00:00Z
        updated_at:
          type: string
          format: date-time
          example: 2021-01-01T00:00:00Z
      required:
        - id
        - url
        - created_at
        - updated_at

    ErrorNotFound:
      type: object
      properties:
        error:
          type: string
          example: Not Found
