redis:
  enabled: true

  serviceMonitor:
    enabled: true
    labels:
      release: prometheus-operator

  prometheusRule:
    enabled: true

  resources:
    limits:
      cpu: 100m
      memory: 350Mi
    requests:
      cpu: 100m
      memory: 128Mi
