argo-cd:
    configs:
        cm:
            url: ENC[AES256_GCM,data:bX2rUw7rneEYWE2iDju+0ySuZNIFrm5VLvBR1w==,iv:5KTzwi3CkwlPFO1v/Zmr69PeGQDbkASlH32QEVJ4A+o=,tag:FlLIYuHru9rdoyo0SHWSsQ==,type:str]
            dex.config: ENC[AES256_GCM,data:jKUGrfepJNh1Zik+aXID8RSWf9z2zL4/liEGMz+yitHVGvphOyRvS8xklZjwFQLczFNq7BRlwiKz0C+MA0iRPVgnecMA2zTmzroHxql4Clr1gefyJs/TlNC1jIkBsLqq+m3Z9tIAArwaDI1z2sx4eRXWabSESf8OFecnQRiMXGrHWC//iVIMyvVQTmZ0Mcc/RxbiXjhvJcj6wRMZe9C3qzUlnbDbM64o1M10LwnkmeDw9/2ov8Y2mULBkse/YBrSbaBHYCBkI/PnC8oB8i9Mj5U1aZUaZULIlzSxCg2zY6ZoJV9SSjJ24mqu24UYxa38fo1gLP8vVY2XuhmRYxNqGBArxcbrlOTLgaUZsmO/P74+3EnVvCijeIUQDB+fwCSmG6QvmbThjUxhKj800dACLtOoB0tafwWXXwAZzAGqhtP/fgUHeeChbNEWdgrFMqhJTsDYe4KS8X1qjrRbGP7Xy0X4GZnUOfcDvNvpcPl8uWo6E/5LIRWo9PotCGZADSE7+GAoZR0IUhIDaXXLC2x0JcrG7B9AadGzpN/JYQ0CwCmFm+RlXq3TYy5DphRBrPb5V67M,iv:aP3r1i42kDZqRkAx75YRSnzItPU9d549VddjQXtMZBA=,tag:WVi8HwqWs73hFfdhi+zzwQ==,type:str]
    notifications:
        secret:
            items:
                slack-token: ENC[AES256_GCM,data:kYpotaZPfGV6Uih7yfJWQ/Y/GrkaZ9XkLzEHBNgBu6VvALk35ekyw1RQ7tb1XtgQ9dy2yQEUJmU=,iv:igcRqi7uSlDp9IV6mOYWx06ojp33c/a4ZTHhfn3CIOA=,tag:48LXSzcI55TZxUvS3pocnA==,type:str]
                grafana-api-key: ENC[AES256_GCM,data:3gTW4/eXOi0KRz1sA8TW5kghI0i6eSyEkJ33QVcbawDpz1P1RcKh0BDMXKmCyw==,iv:hH1FbvKgj6a4jm9R/1cLqtmesn0940iVF8rEoE7NMzo=,tag:q6QAiiTXgg8MH3lzB44KaA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-07-20T14:57:53Z"
    mac: ENC[AES256_GCM,data:q8GokTRmhE8ycDKG/sW4bUhH8f5vDo3oX4GOudTvjPindx51WsGLoRoaRikf2MdC3GpDbFZ5+RG+AdLTmRl+v9URWXmNJoY1Wvov6YnMqCSkkEwSwrBunJwv3fqlbosTK2pvF1V7bS6ZEzxOeaJdCLDz+0g4rLvwdO+Covv2hig=,iv:HOB5ICHXZO1nshs8tWmUm2w4LvSwV20Ch6Yyj23G9r0=,tag:CwKfHYiQjlll7nAPEkKrIQ==,type:str]
    pgp:
        - created_at: "2023-01-15T16:35:29Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAxDrDE6S/SFjAQv+Pyug5MNYLrmGcBrIN2SkR6GF4NTvbwQdBpQsmqZxYEmA
            wtS5D3kXI/Y63G4ITL6iZoi8pjgyVdyyD2oy6+O3Z6nUllAWlQYfzKzZ8JPelYmr
            /Q9Vq59ag2xcFjbFyd1GnAjVy3GF3NR+2VTbEEiCvH5fRWBrrDLUrIpkdy5WUYTX
            S3ic6iZNp73cQku+YYaPCKBeCuZANpO6DxkY63may6cXMWmxaHxGzhIVy/m7Rvd0
            oDYYPPypLpp0HxIlzytcGlMz3W4SNEWbtvCB3DduEYK36MSDIek17rXWrFG9FsZw
            aPe23FEVP21JAiWYwhkBlPpTvbW522TKXuTqNCbfZb5vPbMfMHqIpzL9a4cOudUn
            4f6XlmxO1Y+MliZ5pY2p/tVkyL8FxxNXRzYmwBCHAnJeKrkS5GoZWg3TcHDBiX0S
            VPTuEEDdlxmXPcek08Gz+DM1+HxnrHcGcc5P8fnqcK3j+lrERDxLCeMPltLK/6mA
            +a5TdKPo/h06dfMDCzrP1GgBCQIQu0tnJDEMhIdXb7VyeXRs4IKpS/AhFdMxyRdF
            uQDfWUy8D8cwWAz13R/u8rsDHyb7OSYLG3u8PR+LtE9nT/2sCMpCAPaybpuzlSEV
            df+B8mOhGU2cQzTo05A4NKre7/QKGGVwAQ==
            =441E
            -----END PGP MESSAGE-----
          fp: C92AE33AF20998F8CA09E819A842078E859DE4F1
    unencrypted_suffix: _unencrypted
    version: 3.8.1
