apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: {{ .name | default (include "helpers.fullname" .) }}-test
spec:
  subscriptions:
    repos:
      git:
        - repoURL: https://github.com/shortlink-org/shortlink.git
          branch: main
  promotionMechanisms:
    gitRepoUpdates:
      - repoURL: https://github.com/shortlink-org/shortlink.git
        writeBranch: stage/test
    argoCDAppUpdates:
      - appName: {{ .name | default (include "helpers.fullname" .) }}
        appNamespace: shortlink

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: {{ .name | default (include "helpers.fullname" .) }}-prod
spec:
  subscriptions:
    upstreamStages:
      - name: test
  promotionMechanisms:
    gitRepoUpdates:
      - repoURL: https://github.com/shortlink-org/shortlink.git
        writeBranch: stage/prod
    argoCDAppUpdates:
      - appName: {{ .name | default (include "helpers.fullname" .) }}-prod
        appNamespace: shortlink

---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionPolicy
metadata:
  name: {{ .name | default (include "helpers.fullname" .) }}-promotion
stage: test
enableAutoPromotion: true
