apiVersion: v2
appVersion: "1.0.0"
name: shortlink-link
description: ShortLink link service
version: 0.7.2
kubeVersion: ">= 1.29.0 || >= v1.29.0-0"
keywords:
  - link
  - shortlink
home: https://batazor.github.io/shortlink/
sources:
  - https://github.com/shortlink-org/shortlink
maintainers:
  - email: batazor111@gmail.com
    name: batazor
    url: batazor.ru
engine: gotpl
type: application
deprecated: false
dependencies:
  - name: shortlink-template
    version: 0.8.15
    repository: "file://../shortlink-template"
