x-network: &network
  networks:
    - ${DOCKER_NETWORK}
  dns:
    - ${DNS_IP}
  dns_search: ${DNS_SEARCH}

services:

  tarantool:
    <<: *network
    depends_on:
      - coredns
    image: tarantool/tarantool
    init: true
    restart: on-failure
    container_name: tarantool
    ports:
      - "3301:3301"
