# Common default values for prometheus-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

kube-prometheus-stack:
  enabled: true

  fullnameOverride: prometheus

  grafana:
    enabled: false

  kubeDns:
    enabled: false

  coreDns:
    # disable for GKE
    enabled: true

  prometheus:
    prometheusSpec:
      enableRemoteWriteReceiver: true
      logFormat: json

  prometheusOperator:
    secretFieldSelector: "type!=kubernetes.io/dockercfg,type!=kubernetes.io/service-account-token,type!=helm.sh/release.v1"

    resources:
      limits:
        cpu: 300m
        memory: 200Mi
      requests:
        cpu: 30m
        memory: 50Mi
