# Common default values for prometheus-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

kube-prometheus-stack:
  enabled: true

  fullnameOverride: prometheus

  grafana:
    enabled: false

    sidecar:
      dashboards:
        enableNewTablePanelSyntax: true

  kubeDns:
    enabled: false

  coreDns:
    # disable for GKE
    enabled: true

  prometheus:
    prometheusSpec:
      enforcedKeepDroppedTargets: 1

      resources:
        limits:
          cpu: 1000m
          memory: 2Gi
        requests:
          cpu: 500m
          memory: 256Mi

  prometheusOperator:
    secretFieldSelector: "type!=kubernetes.io/dockercfg,type!=kubernetes.io/service-account-token,type!=helm.sh/release.v1"

    resources:
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 30m
        memory: 50Mi
