opentelemetry-operator:
  enabled: true

  fullnameOverride: opentelemetry-operator

  kubeRBACProxy:
    enabled: true

  manager:
    featureGates:

    serviceMonitor:
      enabled: true

      extraLabels:
        release: prometheus-operator

    prometheusRule:
      enabled: true

      annotations:
        app: opentelemetry-operator

      defaultRules:
        enabled: true

    createRbacPermissions: true
