opentelemetry-operator:
  enabled: true

  kubeRBACProxy:
    enabled: false

  manager:
    image:
      tag: main
    collectorImage:
      tag: 0.90.1

    serviceMonitor:
      enabled: true

    prometheusRule:
      enabled: true

      defaultRules:
        enabled: true
