opentelemetry-operator:
  enabled: true

  kubeRBACProxy:
    enabled: false

  manager:
    serviceMonitor:
      enabled: true

    prometheusRule:
      enabled: true

      annotations:
        app: opentelemetry-operator

      defaultRules:
        enabled: true
