x-network: &network
  networks:
    - ${DOCKER_NETWORK}
  dns:
    - ${DNS_IP}
  dns_search: ${DNS_SEARCH}

services:

  scylla:
    <<: *network
    depends_on:
      - coredns
    image: scylladb/scylla
    container_name: scylla
    init: true
    restart: on-failure
    command: "--smp 1 --memory 256M"
    ports:
      - "9042:9042"
