homepage: "https://shortlink.best/"
language: go
primary_contact: "batazor111@gmail.com"
sanitizers:
  - address
  # Unsupported sanitizers:
  # - undefined
  # - memory
fuzzing_engines:
  - libfuzzer
architectures:
  - x86_64
main_repo: 'https://github.com/shortlink-org/shortlink.git'
