homepage: "https://shortlink.best/"
language: go
primary_contact: "batazor111@gmail.com"
sanitizers:
  - address
  - undefined
  - memory
architectures:
  - x86_64
main_repo: 'https://github.com/shortlink-org/shortlink.git'
