include:
  - local: /ops/gitlab/templates/common.yml
  - local: /ops/gitlab/pipelines/ui/templates/nx.yml
  - local: /ops/gitlab/pipelines/ui/stages/publish.yaml
  - local: /ops/gitlab/pipelines/ui/stages/test.yml
  - local: /ops/gitlab/pipelines/ui/stages/build.yml
  - local: /ops/gitlab/pipelines/ui/stages/accessibility.yml

stages:
  - publish
  - build
  - test # TODO: move after build
  - artifacts
  - deploy
  - accessibility
