.template_build:
  stage: build
  services:
    - name: docker:24.0.7-dind
      command: ["--experimental"]
  image: docker:24.0.7-cli
  variables:
    COSIGN_YES: "true"  # Used by Cosign to skip confirmation prompts for non-destructive operations
    DOCKER_BUILDKIT: 1
    DOCKER_CONTENT_TRUST: 1
    DOCKER_BUILDX_VERSION: v0.12.0
    BUILDX_GIT_LABELS: 1
  id_tokens:
    SIGSTORE_ID_TOKEN: # Used by Cosign to get certificate from Fulcio
      aud: sigstore
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - apk add curl git
    - mkdir -vp ~/.docker/cli-plugins/
    - curl --silent -L "https://github.com/docker/buildx/releases/download/$DOCKER_BUILDX_VERSION/buildx-$DOCKER_BUILDX_VERSION.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
    - chmod a+x ~/.docker/cli-plugins/docker-buildx
    - DOCKER_CONTENT_TRUST=0 docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --use
    - docker buildx inspect --bootstrap
  after_script:
    - apk add --update cosign
    - IMAGE_DIGEST="$(docker inspect --format='{{index .RepoDigests 0}}' "${REGISTRY_IMAGE}:latest")"
    - cosign sign "$IMAGE_DIGEST"
  script:
    - docker buildx build 
      --platform=linux/amd64,linux/arm64
      --provenance=true
      --sbom=true
      --build-arg APP_ENV=ci
      --push $CMD_PATH $DOCKERFILE_ARGS
      -t ${REGISTRY_IMAGE}:latest
      -t ${REGISTRY_IMAGE}:${CI_COMMIT_TAG}
      -f ${DOCKERFILE_PATH} .
  tags:
    - docker
  retry: 2
  rules:
    - when: always
