apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  name: shortlink
spec:
  agentVersion: 3.3.0
  version: 5.4.3
  developerMode: true
  automaticOrphanedNodeCleanup: true
  cpuset: true
  datacenter:
    name: manager-dc
    racks:
      - name: manager-rack
        members: 1
        storage:
          capacity: 2Gi
          storageClassName: local-path
        resources:
          limits:
            cpu: 1
            memory: 100Mi
          requests:
            cpu: 1
            memory: 200Mi
