apiVersion: v1
kind: Namespace
metadata:
  name: local-path-storage
  labels:
    istio-injection: enabled
    # TODO: tuning https://kubernetes.io/docs/concepts/security/pod-security-admission/
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
