shortlink:
  stage: application
  variables:
    PROVIDER: $PROVIDER
    RELEASE_NAME: argo-workflows
    HELM_PATH: ops/Helm/addons/argo/argo-workflows
    HELM_NAMESPACE: argocd
    ENVIRONMENT_URL: https://${ENVIRONMENT_URL}
  trigger:
    include:
      - local: 'ops/gitlab/pipelines/helm_deploy.yml'
    strategy: depend
  needs: []
  rules:
    - when: manual
