argo-cd:
  stage: deploy
  variables:
    PROVIDER: $PROVIDER
    RELEASE_NAME: argocd
    HELM_PATH: ops/Helm/addons/argo/argocd
    HELM_NAMESPACE: argocd
    ENVIRONMENT_URL: https://argo.${ENVIRONMENT_URL}
    HELM_ARG: -f ${HELM_PATH}/values.sops.yaml
  trigger:
    include:
      - local: 'ops/gitlab/pipelines/helm_deploy.yml'
    strategy: depend
  needs: []
  rules:
    - when: manual
