x-network: &network
  networks:
    - ${DOCKER_NETWORK}
  dns:
    - ${DNS_IP}
  dns_search: ${DNS_SEARCH}

services:

  victoria-metrics:
    <<: *network
    depends_on:
      - coredns
    image: victoriametrics/victoria-metrics
    init: true
    restart: on-failure
    container_name: victoria-metrics
    command:
      - -opentsdbHTTPListenAddr=:4242
      - -influxListenAddr=:8089
      - -promscrape.config=/prometheus.yml
    ports:
      - "4242:4242"
      - "8089:8089/tcp"
      - "8089:8089/udp"
      - "8428:8428"
    volumes:
      - ./ops/docker-compose/database/victoria-metrics/conf/prometheus.yml:/prometheus.yml
#      - ./data/shortlink/store/victoria-metrics:/victoria-metrics-data
