version: '2.4'

services:

  cassandra:
    depends_on:
      - coredns
    image: cassandra:4.1.3
    restart: on-failure
    container_name: cassandra
    init: true
    ports:
      - "7000:7000"
      - "9042:9042"
    networks:
      - simple
    dns:
      - ${DNS_IP}
    dns_search: ${DNS_SEARCH}
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 5s
      timeout: 5s
      retries: 60
#    logging:
#      driver: fluent-bit
#      options:
#        tag: cassandra
