# Common default values for temporal.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

temporal:
  enabled: true

  fullnameOverride: temporal

  serviceAccount:
    create: true

  server:
    config:
      persistence:
        default:
          cassandra:
            port: 9042
            hosts:
              - scylla-cluster.temporal

        visibility:
          cassandra:
            port: 9042
            hosts:
              - scylla-cluster.temporal

    metrics:
      serviceMonitor:
        enabled: true

        additionalLabels:
          release: prometheus-operator

    frontend:
      metrics:
        serviceMonitor:
          enabled: true

    history:
      metrics:
        serviceMonitor:
          enabled: true

    matching:
      metrics:
        serviceMonitor:
          enabled: true

    worker:
      metrics:
        serviceMonitor:
          enabled: true

  web:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: cert-manager-production
        nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
        nginx.ingress.kubernetes.io/enable-opentelemetry: "true"

      hosts:
        - "temporal.shortlink.best"

      tls:
        - secretName: temporal-tls
          hosts:
            - "temporal.shortlink.best"

  elasticsearch:
    enabled: true
    replicas: 1

  cassandra:
    enabled: false

  prometheus:
    enabled: false

  grafana:
    enabled: false
