x-network: &network
  networks:
    - ${DOCKER_NETWORK}
  dns:
    - ${DNS_IP}
  dns_search: ${DNS_SEARCH}

services:

  trino:
    <<: *network
    depends_on:
      - coredns
    image: trinodb/trino
    container_name: trino
    restart: on-failure
    ports:
      - "8080:8080"
