apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
spec:
  limits:
    - default:
        memory: 1Gi
        cpu: 1000m
      defaultRequest:
        memory: 128Mi
        cpu: 100m
      type: Container
