# Common default values for scylla-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

scylla-operator:
  enabled: true

scylla-manager:
  enabled: true

  serviceMonitor:
    create: true

scylla:
  enabled: true

  automaticOrphanedNodeCleanup: true

  serviceMonitor:
    create: true
