apiVersion: v2
appVersion: "1.0.0"
name: shortlink-proxy
description: ShortLink service for get proxy by URL
version: 0.3.2
kubeVersion: ">= 1.29.0 || >= v1.29.0-0"
keywords:
  - proxy
  - shortlink
home: https://batazor.github.io/shortlink/
sources:
  - https://github.com/shortlink-org/shortlink
maintainers:
  - email: batazor111@gmail.com
    name: batazor
    url: batazor.ru
engine: gotpl
type: application
deprecated: false
dependencies:
  - name: shortlink-template
    version: 0.8.16
    repository: "file://../shortlink-template"
