cache:
  enabled: true

  # TODO: delete after fix v1.16.1+
  image:
    tag: v1.15.1

  fullnameOverride: cache

  serviceMonitor:
    enabled: true
    labels:
      release: prometheus-operator

  prometheusRule:
    enabled: true

  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
